# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master, dev-gha ]
  pull_request:
    branches: [ master, dev ]

env:
  AUGUR_DB_HOST: localhost
  AUGUR_DB_NAME: test_data
  AUGUR_DB_PORT: 5432
  AUGUR_DB_USER: augur
  AUGUR_DB_PASSWORD: augur

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: before install
      run: |
        docker     strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]run -d -p 5432:5432 --name augur_test_database augurlabs/augur:test_data@sha256:71da12114bf28584a9a64ede2fac0cbc8dffc8e2f4a2c61231206e2f82201c2f
      
    - name: install
      run: |
        ./scripts/install/backend.sh
        ./scripts/install/workers.sh
        augur config init
      
    - name: install tox
      run: |
        python -m pip install --upgrade pip tox tox-gh-actions
      
    - name: tox
      run: |
        tox
